workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    environment:
      java: 17
      android_signing:
        - keystore_reference
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug || gradle wrapper && ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
